defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  password: pass

development:
  database: wasabbi_dev
  username: wasabbi_dev
  owner: wasabbi_dev
  <<: *defaults

test:
  database: wasabbi_test
  username: wasabbi_test
  owner: wasabbi_test
  <<: *defaults

production:
  database: wasabbi
  username: wasabbi_prod
  owner: wasabbi_test
  password: "fill me in"
  host: "fill me in"
  <<: *defaults
